/* tslint:disable */
/* eslint-disable */
/**
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CadenceStream
 */
export interface CadenceStream {
    /**
     * The number of data points in this stream
     * @type {number}
     * @memberof CadenceStream
     */
    originalSize?: number;
    /**
     * The level of detail (sampling) in which this stream was returned
     * @type {string}
     * @memberof CadenceStream
     */
    resolution?: CadenceStreamResolutionEnum;
    /**
     * The base series used in the case the stream was downsampled
     * @type {string}
     * @memberof CadenceStream
     */
    seriesType?: CadenceStreamSeriesTypeEnum;
    /**
     * The sequence of cadence values for this stream, in rotations per minute
     * @type {Array<number>}
     * @memberof CadenceStream
     */
    data?: Array<number>;
}


/**
 * @export
 */
export const CadenceStreamResolutionEnum = {
    Low: 'low',
    Medium: 'medium',
    High: 'high'
} as const;
export type CadenceStreamResolutionEnum = typeof CadenceStreamResolutionEnum[keyof typeof CadenceStreamResolutionEnum];

/**
 * @export
 */
export const CadenceStreamSeriesTypeEnum = {
    Distance: 'distance',
    Time: 'time'
} as const;
export type CadenceStreamSeriesTypeEnum = typeof CadenceStreamSeriesTypeEnum[keyof typeof CadenceStreamSeriesTypeEnum];


/**
 * Check if a given object implements the CadenceStream interface.
 */
export function instanceOfCadenceStream(value: object): value is CadenceStream {
    return true;
}

export function CadenceStreamFromJSON(json: any): CadenceStream {
    return CadenceStreamFromJSONTyped(json, false);
}

export function CadenceStreamFromJSONTyped(json: any, ignoreDiscriminator: boolean): CadenceStream {
    if (json == null) {
        return json;
    }
    return {
        
        'originalSize': json['original_size'] == null ? undefined : json['original_size'],
        'resolution': json['resolution'] == null ? undefined : json['resolution'],
        'seriesType': json['series_type'] == null ? undefined : json['series_type'],
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function CadenceStreamToJSON(json: any): CadenceStream {
    return CadenceStreamToJSONTyped(json, false);
}

export function CadenceStreamToJSONTyped(value?: CadenceStream | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'original_size': value['originalSize'],
        'resolution': value['resolution'],
        'series_type': value['seriesType'],
        'data': value['data'],
    };
}

