/* tslint:disable */
/* eslint-disable */
/**
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface DetailedGear
 */
export interface DetailedGear {
    /**
     * The gear's unique identifier.
     * @type {string}
     * @memberof DetailedGear
     */
    id?: string;
    /**
     * Resource state, indicates level of detail. Possible values: 2 -> "summary", 3 -> "detail"
     * @type {number}
     * @memberof DetailedGear
     */
    resourceState?: number;
    /**
     * Whether this gear's is the owner's default one.
     * @type {boolean}
     * @memberof DetailedGear
     */
    primary?: boolean;
    /**
     * The gear's name.
     * @type {string}
     * @memberof DetailedGear
     */
    name?: string;
    /**
     * The distance logged with this gear.
     * @type {number}
     * @memberof DetailedGear
     */
    distance?: number;
    /**
     * The gear's brand name.
     * @type {string}
     * @memberof DetailedGear
     */
    brandName?: string;
    /**
     * The gear's model name.
     * @type {string}
     * @memberof DetailedGear
     */
    modelName?: string;
    /**
     * The gear's frame type (bike only).
     * @type {number}
     * @memberof DetailedGear
     */
    frameType?: number;
    /**
     * The gear's description.
     * @type {string}
     * @memberof DetailedGear
     */
    description?: string;
}

/**
 * Check if a given object implements the DetailedGear interface.
 */
export function instanceOfDetailedGear(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DetailedGearFromJSON(json: any): DetailedGear {
    return DetailedGearFromJSONTyped(json, false);
}

export function DetailedGearFromJSONTyped(json: any, ignoreDiscriminator: boolean): DetailedGear {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'resourceState': !exists(json, 'resource_state') ? undefined : json['resource_state'],
        'primary': !exists(json, 'primary') ? undefined : json['primary'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'distance': !exists(json, 'distance') ? undefined : json['distance'],
        'brandName': !exists(json, 'brand_name') ? undefined : json['brand_name'],
        'modelName': !exists(json, 'model_name') ? undefined : json['model_name'],
        'frameType': !exists(json, 'frame_type') ? undefined : json['frame_type'],
        'description': !exists(json, 'description') ? undefined : json['description'],
    };
}

export function DetailedGearToJSON(value?: DetailedGear | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'resource_state': value.resourceState,
        'primary': value.primary,
        'name': value.name,
        'distance': value.distance,
        'brand_name': value.brandName,
        'model_name': value.modelName,
        'frame_type': value.frameType,
        'description': value.description,
    };
}

