/* tslint:disable */
/* eslint-disable */
/**
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface DistanceStream
 */
export interface DistanceStream {
    /**
     * The number of data points in this stream
     * @type {number}
     * @memberof DistanceStream
     */
    originalSize?: number;
    /**
     * The level of detail (sampling) in which this stream was returned
     * @type {string}
     * @memberof DistanceStream
     */
    resolution?: DistanceStreamResolutionEnum;
    /**
     * The base series used in the case the stream was downsampled
     * @type {string}
     * @memberof DistanceStream
     */
    seriesType?: DistanceStreamSeriesTypeEnum;
    /**
     * The sequence of distance values for this stream, in meters
     * @type {Array<number>}
     * @memberof DistanceStream
     */
    data?: Array<number>;
}


/**
 * @export
 */
export const DistanceStreamResolutionEnum = {
    Low: 'low',
    Medium: 'medium',
    High: 'high'
} as const;
export type DistanceStreamResolutionEnum = typeof DistanceStreamResolutionEnum[keyof typeof DistanceStreamResolutionEnum];

/**
 * @export
 */
export const DistanceStreamSeriesTypeEnum = {
    Distance: 'distance',
    Time: 'time'
} as const;
export type DistanceStreamSeriesTypeEnum = typeof DistanceStreamSeriesTypeEnum[keyof typeof DistanceStreamSeriesTypeEnum];


/**
 * Check if a given object implements the DistanceStream interface.
 */
export function instanceOfDistanceStream(value: object): value is DistanceStream {
    return true;
}

export function DistanceStreamFromJSON(json: any): DistanceStream {
    return DistanceStreamFromJSONTyped(json, false);
}

export function DistanceStreamFromJSONTyped(json: any, ignoreDiscriminator: boolean): DistanceStream {
    if (json == null) {
        return json;
    }
    return {
        
        'originalSize': json['original_size'] == null ? undefined : json['original_size'],
        'resolution': json['resolution'] == null ? undefined : json['resolution'],
        'seriesType': json['series_type'] == null ? undefined : json['series_type'],
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function DistanceStreamToJSON(json: any): DistanceStream {
    return DistanceStreamToJSONTyped(json, false);
}

export function DistanceStreamToJSONTyped(value?: DistanceStream | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'original_size': value['originalSize'],
        'resolution': value['resolution'],
        'series_type': value['seriesType'],
        'data': value['data'],
    };
}

