/* tslint:disable */
/* eslint-disable */
/**
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { MetaActivity } from './MetaActivity.js';
import {
    MetaActivityFromJSON,
    MetaActivityFromJSONTyped,
    MetaActivityToJSON,
    MetaActivityToJSONTyped,
} from './MetaActivity.js';
import type { MetaAthlete } from './MetaAthlete.js';
import {
    MetaAthleteFromJSON,
    MetaAthleteFromJSONTyped,
    MetaAthleteToJSON,
    MetaAthleteToJSONTyped,
} from './MetaAthlete.js';

/**
 * 
 * @export
 * @interface Lap
 */
export interface Lap {
    /**
     * The unique identifier of this lap
     * @type {number}
     * @memberof Lap
     */
    id?: number;
    /**
     * 
     * @type {MetaActivity}
     * @memberof Lap
     */
    activity?: MetaActivity;
    /**
     * 
     * @type {MetaAthlete}
     * @memberof Lap
     */
    athlete?: MetaAthlete;
    /**
     * The lap's average cadence
     * @type {number}
     * @memberof Lap
     */
    averageCadence?: number;
    /**
     * The lap's average speed
     * @type {number}
     * @memberof Lap
     */
    averageSpeed?: number;
    /**
     * The lap's distance, in meters
     * @type {number}
     * @memberof Lap
     */
    distance?: number;
    /**
     * The lap's elapsed time, in seconds
     * @type {number}
     * @memberof Lap
     */
    elapsedTime?: number;
    /**
     * The start index of this effort in its activity's stream
     * @type {number}
     * @memberof Lap
     */
    startIndex?: number;
    /**
     * The end index of this effort in its activity's stream
     * @type {number}
     * @memberof Lap
     */
    endIndex?: number;
    /**
     * The index of this lap in the activity it belongs to
     * @type {number}
     * @memberof Lap
     */
    lapIndex?: number;
    /**
     * The maximum speed of this lat, in meters per second
     * @type {number}
     * @memberof Lap
     */
    maxSpeed?: number;
    /**
     * The lap's moving time, in seconds
     * @type {number}
     * @memberof Lap
     */
    movingTime?: number;
    /**
     * The name of the lap
     * @type {string}
     * @memberof Lap
     */
    name?: string;
    /**
     * The athlete's pace zone during this lap
     * @type {number}
     * @memberof Lap
     */
    paceZone?: number;
    /**
     * 
     * @type {number}
     * @memberof Lap
     */
    split?: number;
    /**
     * The time at which the lap was started.
     * @type {Date}
     * @memberof Lap
     */
    startDate?: Date;
    /**
     * The time at which the lap was started in the local timezone.
     * @type {Date}
     * @memberof Lap
     */
    startDateLocal?: Date;
    /**
     * The elevation gain of this lap, in meters
     * @type {number}
     * @memberof Lap
     */
    totalElevationGain?: number;
}

/**
 * Check if a given object implements the Lap interface.
 */
export function instanceOfLap(value: object): value is Lap {
    return true;
}

export function LapFromJSON(json: any): Lap {
    return LapFromJSONTyped(json, false);
}

export function LapFromJSONTyped(json: any, ignoreDiscriminator: boolean): Lap {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'activity': json['activity'] == null ? undefined : MetaActivityFromJSON(json['activity']),
        'athlete': json['athlete'] == null ? undefined : MetaAthleteFromJSON(json['athlete']),
        'averageCadence': json['average_cadence'] == null ? undefined : json['average_cadence'],
        'averageSpeed': json['average_speed'] == null ? undefined : json['average_speed'],
        'distance': json['distance'] == null ? undefined : json['distance'],
        'elapsedTime': json['elapsed_time'] == null ? undefined : json['elapsed_time'],
        'startIndex': json['start_index'] == null ? undefined : json['start_index'],
        'endIndex': json['end_index'] == null ? undefined : json['end_index'],
        'lapIndex': json['lap_index'] == null ? undefined : json['lap_index'],
        'maxSpeed': json['max_speed'] == null ? undefined : json['max_speed'],
        'movingTime': json['moving_time'] == null ? undefined : json['moving_time'],
        'name': json['name'] == null ? undefined : json['name'],
        'paceZone': json['pace_zone'] == null ? undefined : json['pace_zone'],
        'split': json['split'] == null ? undefined : json['split'],
        'startDate': json['start_date'] == null ? undefined : (new Date(json['start_date'])),
        'startDateLocal': json['start_date_local'] == null ? undefined : (new Date(json['start_date_local'])),
        'totalElevationGain': json['total_elevation_gain'] == null ? undefined : json['total_elevation_gain'],
    };
}

export function LapToJSON(json: any): Lap {
    return LapToJSONTyped(json, false);
}

export function LapToJSONTyped(value?: Lap | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'activity': MetaActivityToJSON(value['activity']),
        'athlete': MetaAthleteToJSON(value['athlete']),
        'average_cadence': value['averageCadence'],
        'average_speed': value['averageSpeed'],
        'distance': value['distance'],
        'elapsed_time': value['elapsedTime'],
        'start_index': value['startIndex'],
        'end_index': value['endIndex'],
        'lap_index': value['lapIndex'],
        'max_speed': value['maxSpeed'],
        'moving_time': value['movingTime'],
        'name': value['name'],
        'pace_zone': value['paceZone'],
        'split': value['split'],
        'start_date': value['startDate'] == null ? value['startDate'] : value['startDate'].toISOString(),
        'start_date_local': value['startDateLocal'] == null ? value['startDateLocal'] : value['startDateLocal'].toISOString(),
        'total_elevation_gain': value['totalElevationGain'],
    };
}

