/* tslint:disable */
/* eslint-disable */
/**
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface PhotosSummaryPrimary
 */
export interface PhotosSummaryPrimary {
    /**
     * 
     * @type {number}
     * @memberof PhotosSummaryPrimary
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof PhotosSummaryPrimary
     */
    source?: number;
    /**
     * 
     * @type {string}
     * @memberof PhotosSummaryPrimary
     */
    uniqueId?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof PhotosSummaryPrimary
     */
    urls?: { [key: string]: string; };
}

/**
 * Check if a given object implements the PhotosSummaryPrimary interface.
 */
export function instanceOfPhotosSummaryPrimary(value: object): value is PhotosSummaryPrimary {
    return true;
}

export function PhotosSummaryPrimaryFromJSON(json: any): PhotosSummaryPrimary {
    return PhotosSummaryPrimaryFromJSONTyped(json, false);
}

export function PhotosSummaryPrimaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): PhotosSummaryPrimary {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'source': json['source'] == null ? undefined : json['source'],
        'uniqueId': json['unique_id'] == null ? undefined : json['unique_id'],
        'urls': json['urls'] == null ? undefined : json['urls'],
    };
}

export function PhotosSummaryPrimaryToJSON(json: any): PhotosSummaryPrimary {
    return PhotosSummaryPrimaryToJSONTyped(json, false);
}

export function PhotosSummaryPrimaryToJSONTyped(value?: PhotosSummaryPrimary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'source': value['source'],
        'unique_id': value['uniqueId'],
        'urls': value['urls'],
    };
}

