/* tslint:disable */
/* eslint-disable */
/**
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface PhotosSummaryPrimary
 */
export interface PhotosSummaryPrimary {
    /**
     * 
     * @type {number}
     * @memberof PhotosSummaryPrimary
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof PhotosSummaryPrimary
     */
    source?: number;
    /**
     * 
     * @type {string}
     * @memberof PhotosSummaryPrimary
     */
    uniqueId?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof PhotosSummaryPrimary
     */
    urls?: { [key: string]: string; };
}

/**
 * Check if a given object implements the PhotosSummaryPrimary interface.
 */
export function instanceOfPhotosSummaryPrimary(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PhotosSummaryPrimaryFromJSON(json: any): PhotosSummaryPrimary {
    return PhotosSummaryPrimaryFromJSONTyped(json, false);
}

export function PhotosSummaryPrimaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): PhotosSummaryPrimary {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'source': !exists(json, 'source') ? undefined : json['source'],
        'uniqueId': !exists(json, 'unique_id') ? undefined : json['unique_id'],
        'urls': !exists(json, 'urls') ? undefined : json['urls'],
    };
}

export function PhotosSummaryPrimaryToJSON(value?: PhotosSummaryPrimary | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'source': value.source,
        'unique_id': value.uniqueId,
        'urls': value.urls,
    };
}

