/* tslint:disable */
/* eslint-disable */
/**
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface PolylineMap
 */
export interface PolylineMap {
    /**
     * The identifier of the map
     * @type {string}
     * @memberof PolylineMap
     */
    id?: string;
    /**
     * The polyline of the map, only returned on detailed representation of an object
     * @type {string}
     * @memberof PolylineMap
     */
    polyline?: string;
    /**
     * The summary polyline of the map
     * @type {string}
     * @memberof PolylineMap
     */
    summaryPolyline?: string;
}

/**
 * Check if a given object implements the PolylineMap interface.
 */
export function instanceOfPolylineMap(value: object): value is PolylineMap {
    return true;
}

export function PolylineMapFromJSON(json: any): PolylineMap {
    return PolylineMapFromJSONTyped(json, false);
}

export function PolylineMapFromJSONTyped(json: any, ignoreDiscriminator: boolean): PolylineMap {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'polyline': json['polyline'] == null ? undefined : json['polyline'],
        'summaryPolyline': json['summary_polyline'] == null ? undefined : json['summary_polyline'],
    };
}

export function PolylineMapToJSON(json: any): PolylineMap {
    return PolylineMapToJSONTyped(json, false);
}

export function PolylineMapToJSONTyped(value?: PolylineMap | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'polyline': value['polyline'],
        'summary_polyline': value['summaryPolyline'],
    };
}

