/* tslint:disable */
/* eslint-disable */
/**
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface PolylineMap
 */
export interface PolylineMap {
    /**
     * The identifier of the map
     * @type {string}
     * @memberof PolylineMap
     */
    id?: string;
    /**
     * The polyline of the map, only returned on detailed representation of an object
     * @type {string}
     * @memberof PolylineMap
     */
    polyline?: string;
    /**
     * The summary polyline of the map
     * @type {string}
     * @memberof PolylineMap
     */
    summaryPolyline?: string;
}

/**
 * Check if a given object implements the PolylineMap interface.
 */
export function instanceOfPolylineMap(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PolylineMapFromJSON(json: any): PolylineMap {
    return PolylineMapFromJSONTyped(json, false);
}

export function PolylineMapFromJSONTyped(json: any, ignoreDiscriminator: boolean): PolylineMap {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'polyline': !exists(json, 'polyline') ? undefined : json['polyline'],
        'summaryPolyline': !exists(json, 'summary_polyline') ? undefined : json['summary_polyline'],
    };
}

export function PolylineMapToJSON(value?: PolylineMap | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'polyline': value.polyline,
        'summary_polyline': value.summaryPolyline,
    };
}

