/* tslint:disable */
/* eslint-disable */
/**
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { SummarySegmentEffort } from './SummarySegmentEffort.js';
import {
    SummarySegmentEffortFromJSON,
    SummarySegmentEffortFromJSONTyped,
    SummarySegmentEffortToJSON,
    SummarySegmentEffortToJSONTyped,
} from './SummarySegmentEffort.js';
import type { SummaryPRSegmentEffort } from './SummaryPRSegmentEffort.js';
import {
    SummaryPRSegmentEffortFromJSON,
    SummaryPRSegmentEffortFromJSONTyped,
    SummaryPRSegmentEffortToJSON,
    SummaryPRSegmentEffortToJSONTyped,
} from './SummaryPRSegmentEffort.js';

/**
 * 
 * @export
 * @interface SummarySegment
 */
export interface SummarySegment {
    /**
     * The unique identifier of this segment
     * @type {number}
     * @memberof SummarySegment
     */
    id?: number;
    /**
     * The name of this segment
     * @type {string}
     * @memberof SummarySegment
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof SummarySegment
     */
    activityType?: SummarySegmentActivityTypeEnum;
    /**
     * The segment's distance, in meters
     * @type {number}
     * @memberof SummarySegment
     */
    distance?: number;
    /**
     * The segment's average grade, in percents
     * @type {number}
     * @memberof SummarySegment
     */
    averageGrade?: number;
    /**
     * The segments's maximum grade, in percents
     * @type {number}
     * @memberof SummarySegment
     */
    maximumGrade?: number;
    /**
     * The segments's highest elevation, in meters
     * @type {number}
     * @memberof SummarySegment
     */
    elevationHigh?: number;
    /**
     * The segments's lowest elevation, in meters
     * @type {number}
     * @memberof SummarySegment
     */
    elevationLow?: number;
    /**
     * A pair of latitude/longitude coordinates, represented as an array of 2 floating point numbers.
     * @type {Array<number>}
     * @memberof SummarySegment
     */
    startLatlng?: Array<number>;
    /**
     * A pair of latitude/longitude coordinates, represented as an array of 2 floating point numbers.
     * @type {Array<number>}
     * @memberof SummarySegment
     */
    endLatlng?: Array<number>;
    /**
     * The category of the climb [0, 5]. Higher is harder ie. 5 is Hors catégorie, 0 is uncategorized in climb_category.
     * @type {number}
     * @memberof SummarySegment
     */
    climbCategory?: number;
    /**
     * The segments's city.
     * @type {string}
     * @memberof SummarySegment
     */
    city?: string;
    /**
     * The segments's state or geographical region.
     * @type {string}
     * @memberof SummarySegment
     */
    state?: string;
    /**
     * The segment's country.
     * @type {string}
     * @memberof SummarySegment
     */
    country?: string;
    /**
     * Whether this segment is private.
     * @type {boolean}
     * @memberof SummarySegment
     */
    _private?: boolean;
    /**
     * 
     * @type {SummaryPRSegmentEffort}
     * @memberof SummarySegment
     */
    athletePrEffort?: SummaryPRSegmentEffort;
    /**
     * 
     * @type {SummarySegmentEffort}
     * @memberof SummarySegment
     */
    athleteSegmentStats?: SummarySegmentEffort;
}


/**
 * @export
 */
export const SummarySegmentActivityTypeEnum = {
    Ride: 'Ride',
    Run: 'Run'
} as const;
export type SummarySegmentActivityTypeEnum = typeof SummarySegmentActivityTypeEnum[keyof typeof SummarySegmentActivityTypeEnum];


/**
 * Check if a given object implements the SummarySegment interface.
 */
export function instanceOfSummarySegment(value: object): value is SummarySegment {
    return true;
}

export function SummarySegmentFromJSON(json: any): SummarySegment {
    return SummarySegmentFromJSONTyped(json, false);
}

export function SummarySegmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): SummarySegment {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'activityType': json['activity_type'] == null ? undefined : json['activity_type'],
        'distance': json['distance'] == null ? undefined : json['distance'],
        'averageGrade': json['average_grade'] == null ? undefined : json['average_grade'],
        'maximumGrade': json['maximum_grade'] == null ? undefined : json['maximum_grade'],
        'elevationHigh': json['elevation_high'] == null ? undefined : json['elevation_high'],
        'elevationLow': json['elevation_low'] == null ? undefined : json['elevation_low'],
        'startLatlng': json['start_latlng'] == null ? undefined : json['start_latlng'],
        'endLatlng': json['end_latlng'] == null ? undefined : json['end_latlng'],
        'climbCategory': json['climb_category'] == null ? undefined : json['climb_category'],
        'city': json['city'] == null ? undefined : json['city'],
        'state': json['state'] == null ? undefined : json['state'],
        'country': json['country'] == null ? undefined : json['country'],
        '_private': json['private'] == null ? undefined : json['private'],
        'athletePrEffort': json['athlete_pr_effort'] == null ? undefined : SummaryPRSegmentEffortFromJSON(json['athlete_pr_effort']),
        'athleteSegmentStats': json['athlete_segment_stats'] == null ? undefined : SummarySegmentEffortFromJSON(json['athlete_segment_stats']),
    };
}

export function SummarySegmentToJSON(json: any): SummarySegment {
    return SummarySegmentToJSONTyped(json, false);
}

export function SummarySegmentToJSONTyped(value?: SummarySegment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'activity_type': value['activityType'],
        'distance': value['distance'],
        'average_grade': value['averageGrade'],
        'maximum_grade': value['maximumGrade'],
        'elevation_high': value['elevationHigh'],
        'elevation_low': value['elevationLow'],
        'start_latlng': value['startLatlng'],
        'end_latlng': value['endLatlng'],
        'climb_category': value['climbCategory'],
        'city': value['city'],
        'state': value['state'],
        'country': value['country'],
        'private': value['_private'],
        'athlete_pr_effort': SummaryPRSegmentEffortToJSON(value['athletePrEffort']),
        'athlete_segment_stats': SummarySegmentEffortToJSON(value['athleteSegmentStats']),
    };
}

