/* tslint:disable */
/* eslint-disable */
/**
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  DetailedGear,
  Fault,
} from '../models/index.js';
import {
    DetailedGearFromJSON,
    DetailedGearToJSON,
    FaultFromJSON,
    FaultToJSON,
} from '../models/index.js';

export interface GetGearByIdRequest {
    id: string;
}

/**
 * 
 */
export class GearsApi extends runtime.BaseAPI {

    /**
     * Returns an equipment using its identifier.
     * Get Equipment
     */
    async getGearByIdRaw(requestParameters: GetGearByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DetailedGear>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getGearById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("strava_oauth", []);
        }


        let urlPath = `/gear/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DetailedGearFromJSON(jsonValue));
    }

    /**
     * Returns an equipment using its identifier.
     * Get Equipment
     */
    async getGearById(requestParameters: GetGearByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DetailedGear> {
        const response = await this.getGearByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
