/**
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ActivityType } from './activityType';
import { MetaAthlete } from './metaAthlete';
import { SportType } from './sportType';

export class ClubActivity {
    'athlete'?: MetaAthlete;
    /**
    * The name of the activity
    */
    'name'?: string;
    /**
    * The activity\'s distance, in meters
    */
    'distance'?: number;
    /**
    * The activity\'s moving time, in seconds
    */
    'movingTime'?: number;
    /**
    * The activity\'s elapsed time, in seconds
    */
    'elapsedTime'?: number;
    /**
    * The activity\'s total elevation gain.
    */
    'totalElevationGain'?: number;
    'type'?: ActivityType;
    'sportType'?: SportType;
    /**
    * The activity\'s workout type
    */
    'workoutType'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "athlete",
            "baseName": "athlete",
            "type": "MetaAthlete"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "distance",
            "baseName": "distance",
            "type": "number"
        },
        {
            "name": "movingTime",
            "baseName": "moving_time",
            "type": "number"
        },
        {
            "name": "elapsedTime",
            "baseName": "elapsed_time",
            "type": "number"
        },
        {
            "name": "totalElevationGain",
            "baseName": "total_elevation_gain",
            "type": "number"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ActivityType"
        },
        {
            "name": "sportType",
            "baseName": "sport_type",
            "type": "SportType"
        },
        {
            "name": "workoutType",
            "baseName": "workout_type",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return ClubActivity.attributeTypeMap;
    }
}

export namespace ClubActivity {
}
