/**
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MetaActivity } from './metaActivity';
import { MetaAthlete } from './metaAthlete';

export class Lap {
    /**
    * The unique identifier of this lap
    */
    'id'?: number;
    'activity'?: MetaActivity;
    'athlete'?: MetaAthlete;
    /**
    * The lap\'s average cadence
    */
    'averageCadence'?: number;
    /**
    * The lap\'s average speed
    */
    'averageSpeed'?: number;
    /**
    * The lap\'s distance, in meters
    */
    'distance'?: number;
    /**
    * The lap\'s elapsed time, in seconds
    */
    'elapsedTime'?: number;
    /**
    * The start index of this effort in its activity\'s stream
    */
    'startIndex'?: number;
    /**
    * The end index of this effort in its activity\'s stream
    */
    'endIndex'?: number;
    /**
    * The index of this lap in the activity it belongs to
    */
    'lapIndex'?: number;
    /**
    * The maximum speed of this lat, in meters per second
    */
    'maxSpeed'?: number;
    /**
    * The lap\'s moving time, in seconds
    */
    'movingTime'?: number;
    /**
    * The name of the lap
    */
    'name'?: string;
    /**
    * The athlete\'s pace zone during this lap
    */
    'paceZone'?: number;
    'split'?: number;
    /**
    * The time at which the lap was started.
    */
    'startDate'?: Date;
    /**
    * The time at which the lap was started in the local timezone.
    */
    'startDateLocal'?: Date;
    /**
    * The elevation gain of this lap, in meters
    */
    'totalElevationGain'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "activity",
            "baseName": "activity",
            "type": "MetaActivity"
        },
        {
            "name": "athlete",
            "baseName": "athlete",
            "type": "MetaAthlete"
        },
        {
            "name": "averageCadence",
            "baseName": "average_cadence",
            "type": "number"
        },
        {
            "name": "averageSpeed",
            "baseName": "average_speed",
            "type": "number"
        },
        {
            "name": "distance",
            "baseName": "distance",
            "type": "number"
        },
        {
            "name": "elapsedTime",
            "baseName": "elapsed_time",
            "type": "number"
        },
        {
            "name": "startIndex",
            "baseName": "start_index",
            "type": "number"
        },
        {
            "name": "endIndex",
            "baseName": "end_index",
            "type": "number"
        },
        {
            "name": "lapIndex",
            "baseName": "lap_index",
            "type": "number"
        },
        {
            "name": "maxSpeed",
            "baseName": "max_speed",
            "type": "number"
        },
        {
            "name": "movingTime",
            "baseName": "moving_time",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "paceZone",
            "baseName": "pace_zone",
            "type": "number"
        },
        {
            "name": "split",
            "baseName": "split",
            "type": "number"
        },
        {
            "name": "startDate",
            "baseName": "start_date",
            "type": "Date"
        },
        {
            "name": "startDateLocal",
            "baseName": "start_date_local",
            "type": "Date"
        },
        {
            "name": "totalElevationGain",
            "baseName": "total_elevation_gain",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Lap.attributeTypeMap;
    }
}

