/**
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models.js';

export class SummarySegmentEffort {
    /**
    * The unique identifier of this effort
    */
    'id'?: number;
    /**
    * The unique identifier of the activity related to this effort
    */
    'activityId'?: number;
    /**
    * The effort\'s elapsed time
    */
    'elapsedTime'?: number;
    /**
    * The time at which the effort was started.
    */
    'startDate'?: Date;
    /**
    * The time at which the effort was started in the local timezone.
    */
    'startDateLocal'?: Date;
    /**
    * The effort\'s distance in meters
    */
    'distance'?: number;
    /**
    * Whether this effort is the current best on the leaderboard
    */
    'isKom'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "activityId",
            "baseName": "activity_id",
            "type": "number"
        },
        {
            "name": "elapsedTime",
            "baseName": "elapsed_time",
            "type": "number"
        },
        {
            "name": "startDate",
            "baseName": "start_date",
            "type": "Date"
        },
        {
            "name": "startDateLocal",
            "baseName": "start_date_local",
            "type": "Date"
        },
        {
            "name": "distance",
            "baseName": "distance",
            "type": "number"
        },
        {
            "name": "isKom",
            "baseName": "is_kom",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return SummarySegmentEffort.attributeTypeMap;
    }
}

