/**
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models.js';
import { ActivityType } from './activityType.js';
import { SportType } from './sportType.js';

export class UpdatableActivity {
    /**
    * Whether this activity is a commute
    */
    'commute'?: boolean;
    /**
    * Whether this activity was recorded on a training machine
    */
    'trainer'?: boolean;
    /**
    * Whether this activity is muted
    */
    'hideFromHome'?: boolean;
    /**
    * The description of the activity
    */
    'description'?: string;
    /**
    * The name of the activity
    */
    'name'?: string;
    'type'?: ActivityType;
    'sportType'?: SportType;
    /**
    * Identifier for the gear associated with the activity. ‘none’ clears gear from activity
    */
    'gearId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "commute",
            "baseName": "commute",
            "type": "boolean"
        },
        {
            "name": "trainer",
            "baseName": "trainer",
            "type": "boolean"
        },
        {
            "name": "hideFromHome",
            "baseName": "hide_from_home",
            "type": "boolean"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ActivityType"
        },
        {
            "name": "sportType",
            "baseName": "sport_type",
            "type": "SportType"
        },
        {
            "name": "gearId",
            "baseName": "gear_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return UpdatableActivity.attributeTypeMap;
    }
}

export namespace UpdatableActivity {
}
