/**
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models.js';

export class Upload {
    /**
    * The unique identifier of the upload
    */
    'id'?: number;
    /**
    * The unique identifier of the upload in string format
    */
    'idStr'?: string;
    /**
    * The external identifier of the upload
    */
    'externalId'?: string;
    /**
    * The error associated with this upload
    */
    'error'?: string;
    /**
    * The status of this upload
    */
    'status'?: string;
    /**
    * The identifier of the activity this upload resulted into
    */
    'activityId'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "idStr",
            "baseName": "id_str",
            "type": "string"
        },
        {
            "name": "externalId",
            "baseName": "external_id",
            "type": "string"
        },
        {
            "name": "error",
            "baseName": "error",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        },
        {
            "name": "activityId",
            "baseName": "activity_id",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Upload.attributeTypeMap;
    }
}

