# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: shamvelo

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs4.3
  memorySize: 256
  cfLogs: true

  # you can overwrite defaults here
  stage: dev
  region: ap-southeast-2

  # you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "lambda:InvokeFunction"
      Resource:
        "Fn::GetAtt":
          - RefreshAthleteImplLambdaFunction
          - Arn
    - Effect: "Allow"
      Action:
        - "lambda:InvokeFunction"
      Resource:
        "Fn::GetAtt":
          - RefreshAthleteActivitiesImplLambdaFunction
          - Arn
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
        - "s3:PutObject"
      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ActivityBucket" }, "/*" ] ] }
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ActivityBucket" } ] ] }
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
        - "s3:PutObject"
      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "AthleteBucket" }, "/*" ] ] }
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "AthleteBucket" } ] ] }
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
        - "s3:PutObject"
      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "TokenBucket" }, "/*" ] ] }
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "TokenBucket" } ] ] }
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
        - "s3:PutObject"
      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ViewBucket" }, "/*" ] ] }
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ViewBucket" } ] ] }

# you can add packaging information here
#package:
#  exclude:
#    - exclude-me.js
#  artifact: my-service-code.zip

functions:
  getRegisterRedirect:
    handler: handler.getRegister
    events:
      - http:
          path: register
          method: get
  getRegisterCode:
    handler: handler.getRegisterCode
    events:
      - http:
          path: registercode
          method: get
  getRegisterToken:
    handler: handler.getRegisterToken
    events:
      - http:
          path: registertoken
          method: get
  refreshAthleteOnRequest:
    handler: handler.refreshAthleteOnRequest
    events:
      - http:
          path: athlete/{athleteId}/refresh
          method: post
  refreshAthleteOnTokenChange:
    handler: handler.refreshAthleteOnTokenChange
  refreshAthleteImpl:
    handler: handler.refreshAthleteImpl
  buildHomeView:
    handler: handler.buildHomeView
  getHomeView:
    handler: handler.getHomeView
    events:
      - http:
          path: home
          method: get
  buildAthleteView:
    handler: handler.buildAthleteView
  getAthleteView:
    handler: handler.getAthleteView
    events:
      - http:
          path: athlete/{athleteId}
          method: get
  refreshAllActivities:
    timeout: 300
    handler: handler.refreshAllActivities
    events:
      - schedule: rate(1 hour)
  refreshAthleteActivitiesOnRequest:
    handler: handler.refreshAthleteActivitiesOnRequest
    events:
      - http:
          path: athlete/{athleteId}/refreshactivities
          method: post
  refreshAthleteActivitiesOnAthleteChange:
    timeout: 60
    handler: handler.refreshAthleteActivitiesOnAthleteChange
  refreshAthleteActivitiesImpl:
    timeout: 60
    handler: handler.refreshAthleteActivitiesImpl
  buildLeaderboardView:
    timeout: 30
    handler: handler.buildLeaderboardView
  getLeaderboardView:
    handler: handler.getLeaderboardView
    events:
      - http:
          path: leaderboard
          method: get
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get

# you can add CloudFormation resource templates here
resources:
  Resources:
    ActivityBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-${self:provider.stage}-activity
        NotificationConfiguration:
          LambdaConfigurations:
            - Event: s3:ObjectCreated:*
              Function:
                "Fn::GetAtt":
                  - BuildLeaderboardViewLambdaFunction
                  - Arn
    BuildLeaderboardViewLambdaPermissionS3:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName:
          "Fn::GetAtt":
            - BuildLeaderboardViewLambdaFunction
            - Arn
        Action: lambda:InvokeFunction
        Principal: s3.amazonaws.com
        SourceArn: arn:aws:s3:::${self:service}-${self:provider.stage}-activity
    AthleteBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-${self:provider.stage}-athlete
        NotificationConfiguration:
          TopicConfigurations:
            - Event: s3:ObjectCreated:*
              Topic:
                Ref: AthleteUpdateTopic
    TokenBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-${self:provider.stage}-token
        NotificationConfiguration:
          LambdaConfigurations:
            - Event: s3:ObjectCreated:*
              Function:
                "Fn::GetAtt":
                  - RefreshAthleteOnTokenChangeLambdaFunction
                  - Arn
    RefreshAthleteOnTokenChangeLambdaPermissionS3:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName:
          "Fn::GetAtt":
            - RefreshAthleteOnTokenChangeLambdaFunction
            - Arn
        Action: lambda:InvokeFunction
        Principal: s3.amazonaws.com
        SourceArn: arn:aws:s3:::${self:service}-${self:provider.stage}-token
    ViewBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-${self:provider.stage}-view
    AthleteUpdateTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:service}-${self:provider.stage}-athlete
        Subscription:
          - Endpoint:
              "Fn::GetAtt":
                - BuildAthleteViewLambdaFunction
                - Arn
            Protocol: lambda
          - Endpoint:
              "Fn::GetAtt":
                - BuildHomeViewLambdaFunction
                - Arn
            Protocol: lambda
          - Endpoint:
              "Fn::GetAtt":
                - RefreshAthleteActivitiesOnAthleteChangeLambdaFunction
                - Arn
            Protocol: lambda
    BuildAthleteViewLambdaPermissionSNS:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName:
          "Fn::GetAtt":
            - BuildAthleteViewLambdaFunction
            - Arn
        Action: lambda:InvokeFunction
        Principal: sns.amazonaws.com
        SourceArn:
          "Fn::Join" :
            - ""
            - - "arn:aws:sns:"
              - Ref: AWS::Region
              - ":"
              - Ref: AWS::AccountId
              - ":"
              - Ref: AthleteBucket
    BuildHomeViewLambdaPermissionSNS:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName:
          "Fn::GetAtt":
            - BuildHomeViewLambdaFunction
            - Arn
        Action: lambda:InvokeFunction
        Principal: sns.amazonaws.com
        SourceArn:
          "Fn::Join" :
            - ""
            - - "arn:aws:sns:"
              - Ref: AWS::Region
              - ":"
              - Ref: AWS::AccountId
              - ":"
              - Ref: AthleteBucket
    RefreshAthleteActivitiesOnAthleteChangeLambdaPermissionSNS:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName:
          "Fn::GetAtt":
            - RefreshAthleteActivitiesOnAthleteChangeLambdaFunction
            - Arn
        Action: lambda:InvokeFunction
        Principal: sns.amazonaws.com
        SourceArn:
          "Fn::Join" :
            - ""
            - - "arn:aws:sns:"
              - Ref: AWS::Region
              - ":"
              - Ref: AWS::AccountId
              - ":"
              - Ref: AthleteBucket

    IamPolicyAthleteTopic:
      Type: AWS::SNS::TopicPolicy
      Properties:
        PolicyDocument:
          Id: AthleteBucketNotificationPolicy
          Version: "2012-10-17"
          Statement:
            - Sid: AllowBucketToNotifyAthleteUpload
              Effect: Allow
              Principal:
                Service: s3.amazonaws.com
              Action:
                - sns:Publish
              Resource:
                Ref: AthleteUpdateTopic
              Condition:
                ArnLike:
                  aws:SourceArn: arn:aws:s3:*:*:${self:service}-${self:provider.stage}-athlete
        Topics:
          - Ref: AthleteUpdateTopic
